### ISSUE TITLE
传播特征问卷设计

### ISSUE THREAD

**Issue by doomooo** [social-innovation/tasks#10]
**背景**

为了获取特定人群的传播特征，需要对特定人群进行问卷调查

**目的**

> 问卷需要满足的要求
- 题目科学合理，能够覆盖大多数传播特征
- 合理处理敏感问题
- 不同人群采用不同的问卷

> 线下调查员行动指南要求
- 行动指南切实可行
- 可以较好调动被调查者的积极性

**实现**

- 阅读已有资料，了解项目背景与问卷目的
- 假设传播特征，并据此设计问题
- 合理处理敏感问题
- 设计的问卷以Markdown形式呈现（或者word）
- 自行设计问卷排版

**要求**

- 证明自己有能力进行此项工作
- 通过思考与沟通明确需求
- 明确需求后，在承诺的时间完成问卷设计
- 需要提供问卷的设计理由，包括假设的传播特征，敏感问题的处理等关键点的处理理由

**参考**

- 参考资料包括项目中已有的问卷，访谈记录资料，由 @liyutong001  提供
- 问卷简单注意点（https://shimo.im/docs/u8pOszSSoqABwTBM/ 「问卷设计--如何提高问卷的可靠性」）

**Comment by doomooo** [comment]
@ben7th @liyutong001  评估一下上述任务目标是否清晰合理

**Comment by ben7th** [comment]
@doomooo 

这是一个数据整理工作，还是一个开发工作，还是一个需要有心理学知识背景，并贡献心理学知识的工作？

提交物应该是符合一定格式的文本，不能是 word （程序无法处理）

**Comment by doomooo** [comment]
@ben7th 
这个工作是根据已知情况设计问卷。
心理学背景或者文科背景有助于工作的开展，但也不是必备条件。

**Comment by ben7th** [comment]
@doomooo 问卷会怎么被使用？

- 线下发放？
- 使用程序调用问卷数据，通过一个 UI 让被调查者操作？

@liyutong001 目前的参考是怎样的？这个工作是偏撰写还是偏整理？

**Comment by doomooo** [comment]
@ben7th 
问卷使用是采用项目之前的方法（线下网格员）
工作主要是对这个部分的重新撰写
https://github.com/social-innovation/d-net-group/issues/9

**Comment by ben7th** [comment]
@doomooo 也就是说，撰写 + 整理一篇调查问卷文档，用于指导线下工作。我的理解没错吧？

石墨文档看不了，你授权给我一下（ben7th@sina.com）

建议：

- 问卷以规范的纯文本形式表示每个问题以及选项。这样便于数据回收。

**Comment by doomooo** [comment]
@ben7th 

是的。

石墨已授权。

**Comment by ben7th** [comment]
@doomooo 简单注意点并不是很长，可以直接写在任务要求里，或者把石墨文档做成公开访问的

**Comment by doomooo** [comment]
@ben7th  

嗯嗯，链接已公开访问

**Comment by liyutong001** [comment]
@ben7th ,这个工作其实是偏构思、撰写；
@doomooo ，可能还需要考虑这类调查问卷的具体实用性。建议先看看如下论坛中的具体社工访谈内容，来设计问卷：
http://www.cszqss.com/xuexi.asp

**Comment by doomooo** [comment]
@liyutong001 

里面的内容已经看了，这些资料都可给开发者做参考。（这个社工网站链接今天打不开了）

**Comment by liyutong001** [comment]
@doomooo ，那个网站的域名改了，从.com--->.org， 可以访问http://www.cszqss.org/xuexi.asp

**Comment by doomooo** [comment]
@ben7th  @liyutong001 

关于这个问卷设计需求还需要完善和明确的吗？

**Comment by ben7th** [comment]
@doomooo 

这项工作是由你来执行，还是你来管理，发包找其他人执行？

你根据这个模板：
https://github.com/social-innovation/tasks/blob/master/mart-task-template.md
补充内容，在这个 repo 下面新发一个 issue
进行码市发包

若是由你来做，你明确提交物，阶段时间承诺后，在码市报名；
若是由其他人来做，你监督报名者对提交物和阶段时间的承诺，负责管理审核与 review

**Comment by doomooo** [comment]
@ben7th 

这个项目还是由其他人来完成吧，这种文科性质的事情我不太适合。

对于这个项目我是希望能有文科背景的人参与，看看能不能带来一些新的想法。 我想先看看有没有南大的社会学专业的同学愿意参加，他们对于问卷这一块应该是比较适合的。

**Comment by ben7th** [comment]
@doomooo 好的，若有合适的人再好不过

另外看你是否有时间在这个过程中进行发包，文档管理，以及进度跟踪（因为文科背景的同学可能不习惯使用 github 来提交内容和沟通）

**Comment by doomooo** [comment]
@ben7th 

已经找到社会学专业的同学来做这个问卷设计，她们平时问卷设计的比较多。

另外，也已经发了新的issue。

**Comment by ben7th** [comment]
@doomooo 好的，那这个 issue 我关闭了。

引用一下新 issue:
https://github.com/social-innovation/tasks/issues/18
