### ISSUE TITLE
宋哥，我们找到一个合适的算法，代码是python2，正在调试，具体的已经上传到文本分析情感算法模块。

### ISSUE THREAD

**Issue by Zhouyl94** [social-innovation/tasks#14]
@ben7th

**Comment by fushang318** [comment]
@Zhouyl94 别乱建ISSUE

**Comment by Zhouyl94** [comment]
@fushang318 不好意思，这个能删掉么？

**Comment by ben7th** [comment]
@Zhouyl94 沟通请在
https://github.com/social-innovation/cooperation-buaa

发 issue
这里只能发任务 issue
