### ISSUE TITLE
开发数据获取服务

### ISSUE THREAD

**Issue by ben7th** [social-innovation/tasks#17]
### 1、目标

目前有若干数据运算模块需要用到不同的输入数据；
不同的运算模块采用不同的语言或框架编写，为了使得数据传递更规范化，减少开发成本，需要实现供各个数据运算模块使用的数据获取服务；以达到以下目标：

- 使得各个数据运算模块能够通过统一的 HTTP API 接口获取 json 数据
- 根据传入的数据源名称，找到对应的表（mysql 的表或者 mongoDB 的 collection），将表内的数据以 json 形式返回
- 支持分页获取数据

#### 1.1、选型/环境

- 需要访问的数据存储在 mongoDB 或 mysql 中
- 使用 python3 实现数据获取服务以及 HTTP API
- 服务部署在阿里云上

#### 1.2、文档

- 通过沟通确认需求，提交需求理解文档
- 确定需求理解后，完成设计，提交设计文档

#### 1.3、开发

- 实现 HTTP 服务
- 实现支持分页获取数据的 HTTP API
- 通过配置文件或配置记录表维护数据源名称和实际数据库表之间的映射关系

#### 2.1、阶段和验收

周期：10 天（明确需求后，以开发者承诺为准）

#### 2.2、调整和处罚（码市）

- 可以进行一次时间调整申请，最长不超过 2 天。
- 未申请或已经有过调整的，每延期一天按项目金额的 10% 进行罚款。
- 超过 5 天，需求方有权取消项目。
- 需求方原因造成的延误不包含在内。

#### 3.1、人员要求

- 证明自己有能力胜任此项工作
- 通过沟通与思考明确需求
- 明确需求后，在承诺的时间完成提交
- 熟悉 github
- 熟悉 python 以及相关 http 实现框架
- 熟悉 mysql, mongodb

### 4、费用

2000 元（理解需求后按实际承诺工作量计算）

### 5、协作工具

- zoom: https://zoom.us/
- 石墨文档: https://shimo.im/
- github: https://github.com/
- 阿里云账号
- 微信

**Comment by jhdxr** [comment]
歪个楼，你的头像是不思议迷宫的冈布奥抱枕么→_→

**Comment by ben7th** [comment]
@jhdxr 是 DQ 里面的史莱姆啊

**Comment by zfxSteven** [comment]
你那里有没有再详细一点的说明啊

**Comment by fushang318** [comment]
@zfxSteven 你觉得哪些地方不够详细或者是疑惑可以具体说明一下

**Comment by zfxSteven** [comment]
1.你这是多个数据系统的统一数据合并吗？
2.加一层的数据接口开发？
3.有哪些数据来源，都是什么样的数据，开发需求有没有收集完全？
4.发回的数据结果是动态生成（直接分配到不同的数据库中查询），还每天增量抽取到中间库？
5.后台仅需要生成日志（简单/详细？）还是要有后台管理功能和页面？
6.可以用restful API的形式实现吗？
7.允不允许兼职？

**Comment by fushang318** [comment]
@zfxSteven 

> 1.你这是多个数据系统的统一数据合并吗？
> 2.加一层的数据接口开发？
> 3.有哪些数据来源，都是什么样的数据，开发需求有没有收集完全？
> 4.发回的数据结果是动态生成（直接分配到不同的数据库中查询），还每天增量抽取到中间库？

每种算法需要的数据都保存在几个固定的数据库表中，这个服务直接从数据库读取数据  
目前还没有全部完成算法的开发，所以需要先设计和实现好一种后续可以比较容易集成新算法的形式

> 5. 后台仅需要生成日志（简单/详细？）还是要有后台管理功能和页面？

可以先提供通过 yaml 配置文件方式实现每种算法需要的配置

> 6. 可以用restful API的形式实现吗？ 

可以

> 7. 允不允许兼职？ 

允许并且提倡

**Comment by ben7th** [comment]
@zfxSteven 

若有兴趣参与，可以提交一份需求理解或问题清单（不用太长，一页纸）
并通过码市 https://mart.coding.net/project/11602 报名，写明 github 账号

**Comment by Qin21** [comment]
我是覃虹榕，此条消息已在码发包。

**Comment by ben7th** [comment]
此工作推迟进行，issue 关闭
