### ISSUE TITLE
对 DBpedia 的指定类型数据进行采集与编排

### ISSUE THREAD

**Issue by ben7th** [social-innovation/tasks#20]
### 1、目标

目前因为研究工作，需要获取一些结构化的词条信息，用来在特定领域，针对特定数据集合辅助进行监督式学习。因此，需要从 DBpedia 采集指定类型的数据，以达到以下目标：

- 数据具有明确的结构化，有严格内在逻辑，经过一定的组织
- 数据能够被装入 mongoDB 这样的 NoSQL 数据库，便于本地检索

希望有熟悉 DBpedia 的开发者或研究者指导我们具体应该如何去做

#### 1.1、选型/环境

- 使用 python3 或其他常见语言编写数据采集工具（爬虫）
- 使用 mongoDB 存储数据（架设在阿里云上）
- 采集来的数据以 JSON 形式表示

#### 1.2、文档

- 希望对 DBpedia 有使用经验的朋友能和我们聊聊，理解我们要做的事情，给我们一些执行方法上的建议文档。（只要给出有价值，可操作的建议，就可以支付一定费用）
- 对于数据采集工具的设计，对于 DBpedia 数据源的处理，以及采集结果数据的结构编排，给出设计文档

#### 1.3、开发

- 实现数据采集工具的开发
- 配合运维工程师实现 CI/CD
- 帮助研究团队完成首批指定参数的数据采集，存入指定数据库

#### 2.1、阶段和验收

周期：10 天（明确需求后，以开发者承诺为准）

#### 2.2、调整和处罚（码市）

- 可以进行一次时间调整申请，最长不超过 2 天。
- 未申请或已经有过调整的，每延期一天按项目金额的 10% 进行罚款。
- 超过 5 天，需求方有权取消项目。
- 需求方原因造成的延误不包含在内。

#### 3.1、人员要求

- 证明自己有能力胜任此项工作
- 通过沟通与思考明确需求
- 明确需求后，在承诺的时间完成提交
- 熟悉 github, github 账号时间大于半年（在报名中给出 github 账号）
- 熟悉 DBpedia, WikiPedia, 语义网相关知识
- 熟悉数据采集/爬虫类工具开发

报名人员可到：
[github.com/social-innovation/tasks/issues/20](https://github.com/social-innovation/tasks/issues/20)
直接进行需求讨论

### 4、费用

1500 元（理解需求后按实际承诺工作量计算）

### 5、协作工具

- zoom: https://zoom.us/
- 石墨文档: https://shimo.im/
- github: https://github.com/
- 微信

**Comment by ben7th** [comment]
@liyutong001 看看是否还需要补充或修改要求，或者补充目标

**Comment by liyutong001** [comment]
@ben7th 我修改了数据源，改成，Freebase与DBpedia ，看看是要另外开一个任务，还是放在一起。

**Comment by ben7th** [comment]
@liyutong001 
可以告诉我，由我来修改，直接修改的话，我不容易得知修改了哪些地方
另外建议分开，即使两个都需要做，也要先从一个做起
因为我们没有做过这样的事情，需要先进行一次，以明确整个过程中涉及的沟通，协调，需求

**Comment by Qin21** [comment]
此任务已在码市发包：https://mart.coding.net/project/11930

**Comment by XiaohuanIT** [comment]
DBpedia这类数据，我没有爬过，其他的都了解熟悉。已经在码市上申请加入了项目，新手，不熟悉你们的具体要求，以及不确定你们的十天时间是否匆忙。

**Comment by Qin21** [comment]
DBpedia 的指定类型数据进行采集与编排任务第一位应聘者杨晓欢：https://mart.coding.net/p/11930

**Comment by samjjx** [comment]
码市上看到的，你们的需求很不明确啊。我处理过dbpedia数据集，这个数据集隔一段时间就会推送一个新的版本，但是看你们的文档没说清楚。能把需求说清楚一些吗？我看能不能接包。

**Comment by liyutong001** [comment]
@samjjx ，我们需要针对某一领域（如禁毒与社会治理），提取dbpedia中的相关概念、实体、同一关系（类似词SameAs）、概念-子概念关系、概念-实体关系、相关属性等，整理后，作为领域知识图谱的参考资料。

**Comment by liyutong001** [comment]
@XiaohuanIT ，也请你参考上面一条回复。

**Comment by liyutong001** [comment]
@XiaohuanIT ，@samjjx  若有相关经验的话，也请你们针对领域知识图谱的构建思路，提出你们自己的想法或建议吧。

**Comment by XiaohuanIT** [comment]
我对自然语言处理这块还比较熟悉，知识图谱方面，目前也是我的研究方向。我对关系抽取方面，稍微更熟悉一点。目前我的空余时间较多，也想往这个方面多学习。http://kw.fudan.edu.cn/cndbpedia/search/   这种，我个人觉得做得还是挺好的

**Comment by liyutong001** [comment]
@XiaohuanIT ,你可以简要写一下你打算如何完成这个任务，描述大致的思路与提交物，以及这样做的理由。请先聚焦在当前的具体问题的解决上。

**Comment by ben7th** [comment]
目前的总体思路不会直接用到 dbpedia，此 issue 关闭
