### ISSUE TITLE
进行文本向量化运算模块开发与封装

### ISSUE THREAD

**Issue by ben7th** [social-innovation/tasks#21]
### 1、目标

目前因为研究工作，需要对大量文本进行事件提取（event-extraction），我们打算使用监督式机器学习的做法进行实验。其中一个必要的步骤是文本向量化的实现；

我们希望实现能够支持文本向量化运算工作的算法模块，以实现以下目标：

- 对指定的输入文本内容（以字符串形式表示）进行运算，生成文本向量化矩阵；
- 将向量化矩阵以严格的形式输出到文件/保存到数据库
- 能够在向量化的过程中，指定必要的参数
- 对中文有良好的支持

#### 1.1、选型/环境

- 使用 python3 编写文本向量化模块（核心算法可自由引用其他第三方实现，或自行实现）
- 编码需严格符合提交规范：http://t.cn/RH62phO
- 输出文件以 JSON 或 CSV 形式表示
- 数据库使用 mongoDB （架设在阿里云）

#### 1.2、文档

- 希望对文本向量化方法有一定开发经验的朋友能和我们聊聊，理解我们要做的事情，给我们一些执行方法上的建议文档。（只要给出有价值，可操作的建议，就可以支付一定费用）
- 对于算法模块的设计，给出接口文档，包括对输入数据格式，输出数据格式的严格定义

#### 1.3、开发

- 实现文本向量化模块的开发
- 配合运维工程师实现 CI/CD
- 选择一定量（不小于 1000 篇）的公共领域的新闻文稿作为实验数据，检测算法模块，生成结果数据

#### 2.1、阶段和验收

周期：10 天（明确需求后，以开发者承诺为准）

#### 2.2、调整和处罚（码市）

- 可以进行一次时间调整申请，最长不超过 2 天。
- 未申请或已经有过调整的，每延期一天按项目金额的 10% 进行罚款。
- 超过 5 天，需求方有权取消项目。
- 需求方原因造成的延误不包含在内。

#### 3.1、人员要求

- 证明自己有能力胜任此项工作
- 通过沟通与思考明确需求
- 明确需求后，在承诺的时间完成提交
- 熟悉文本处理相关知识
- 能够理解并严格遵循提交规范
- 熟悉 python3 以及相关的算法开发

报名人员可到：
[github.com/social-innovation/tasks/issues/21](https://github.com/social-innovation/tasks/issues/21)
直接进行需求讨论

### 4、费用

1500 元（理解需求后按实际承诺工作量计算）

### 5、协作工具

- zoom: https://zoom.us/
- 石墨文档: https://shimo.im/
- github: https://github.com/
- 微信

**Comment by ben7th** [comment]
@liyutong001 看看是否还需要补充或修改要求，或者补充目标

**Comment by liyutong001** [comment]
@doomooo ，你看看是否有何想法，哪些需要修改完善的。

**Comment by ben7th** [comment]
@doomooo 我觉得我写的要求可能专业性不够，你看看工作目标描述中是否还需要一些支撑条件

**Comment by doomooo** [comment]
@liyutong001 

这个需求的工作量可能有点大，可以分两步

- 首先是将事件结构化，即根据事件创建事件知识谱
- 再将事件知识谱转化为向量（可以参考词向量生成方法）

@ben7th 

目前的表述感觉有点泛，提交物不太好定性检验

可以增加这样的要求：

- 相似的文本信息，其对应的文本向量也应该相似
- 自行设计方案，能定量检验结果

今天也可以开会讨论一下？

**Comment by ben7th** [comment]
@doomooo 如果是以特定类型的文档，比如新闻稿，选择特定的向量化方式，先做一遍如何？
只要能先确定这个模块的输入和输出结构，那么其他集成工作就可以尽快开始。
把整个架子搭起来之后，再在这个架子上检查和优化结果.

后面不管换什么特定领域或特定来源的文本，只要把变化范围局限在参数的变化，向量化算法的变化，参考知识谱的变化，而输入输出结构不变，原来的软件架构就可以持续使用

**Comment by liyutong001** [comment]
@doomooo ，可以按你的想法再来修改、具体化一下，你先写出来；
@ben7th ，@doomooo ，今天晚上8点30开会讨论一下吧。

**Comment by doomooo** [comment]
@ben7th 

先把架子搭起来也是可以的，不过需要先明确如何检验提交物，除了数据格式的要求，另外还需要添加结果质量的考察。

建议：

- 文本之间的相似度，与其对应的文本向量之间的相似度成正比
- 自行设计检验方案  （挑选几篇文本作为测试集，自行设定文本之间的相似度）



@ben7th   @liyutong001 

但是，如果该工作未来的输入可能包括小的事件（具体到个人的事件，每个事件文本可能就一两句话），这种文本输入和现在的新闻稿作为输入，两者的区别应该很大的，那么用同一个算法模块来计算文本向量，可能效果不太好。

而如果，统一先变成结构化的信息，然后再由结构化的信息作为输入得到对应的文本向量，可能具有更强的通用性。

如果将这两种文本输入独立分开做的话，也是可以的，可能效果更好，不过就是通用性不太强。

未来的输入文本可能比较多元的话，还是建议先结构化。

**Comment by doomooo** [comment]
@ben7th  @liyutong001 

可以晚上讨论一下具体的文本输入有哪些，以及预期的效果。

**Comment by ben7th** [comment]
@doomooo 将来算法参数和参考的词库等一定是会更换的
只要保证输出结构不变，现在架设起来的架构，将来就可以使用。

我的考虑，现阶段：

1. 先基于新闻文稿，选择合适的变量（参数，词库，其他）做一个文本向量化模块，称为 A
2. 确定 A 的输入输出，让工程师围绕 A 架设其余软件架构设施：`X - Y - A - Z - U`
3. 在合适的时间，通过不断时间，选择出新的合适的变量（参数，词库，其他）做另一个针对其他领域特征文本的向量化模块，称为 B
4. 只要保证 A 和 B 的输入输出结构是一致的，那么之前架设的其余设施 X Y Z U 就可以继续使用。
5. 事实上，最后不管是 `X - Y - A - Z - U` `X - Y - B - Z - U` `X - Y - C - Z - U` 只是在更换算法模块。
6. 所以，现在 A 只要做到能够促进 X Y Z U 的开发就可以了，优先关注 A 的输入输出结构，至于 A 本身的质量可以晚一些关注。不然，等到 A 做到一个合理的质量，再去做 X Y Z U，工程上的等待就太多了。

**Comment by doomooo** [comment]
@ben7th 

嗯嗯，这样的考虑比较有利于性项目的同步进行，可以先做，看看效果怎么样。

**Comment by liyutong001** [comment]
@ben7th @doomooo （1）关于今天上午讨论到的Dbpeadia的具体输出：
DBPedia: DBPedia是早期的语义网项目。DBPedia意指数据库版本的Wikipedia，是从Wikipedia抽取出来的链接数据集。DBPedia采用了一个较为严格的本体，包含人、地点、音乐、电影、组织机构、物种、疾病等类定义。此外，DBPedia还与Freebase，OpenCYC、Bio2RDF等多个数据集建立了数据链接。DBPedia采用RDF语义数据模型，总共包含30亿RDF三元组。
（来自http://www.cnblogs.com/timdes1/p/7504430.html）

（2）关于RDF的简要介绍：
http://programmer.zhujunwu.cn/article/27948

**Comment by liyutong001** [comment]
@ben7th @doomooo 找到一些开放数据集和开源工具：
（1）数据集http://openkg.cn/dataset ，其中有76个中文的json格式或txt格式等数据集，其中就有中文的csv格式的数据集http://openkg.cn/dataset/cndbpedia
（2）工具http://openkg.cn/tool，其中有44个工具，以python和Java为主，看能否参考一下。

**Comment by liyutong001** [comment]
@ben7th @doomooo 部分元数据源（Knowledge Graph,freebase, 与dbpedia类似的wikidata）数据抓取输出样例 http://blog.csdn.net/tobacco5648/article/details/50513949

**Comment by ben7th** [comment]
![image](https://user-images.githubusercontent.com/322486/34460487-e684ae96-ee4a-11e7-9770-e8405ed58a64.png)

TODO：需根据讨论后形成的上图重新划分任务
