### ISSUE TITLE
使用阿里云数+平台进行数据统计和制定开发规范

### ISSUE THREAD

**Issue by fushang318** [social-innovation/tasks#25]
### 1、目标

目前有一些数据，样例如下   

用户ID | 所属社区编号 | 创建时间 | 其他业务字段略过
------------ | ------------- | ------------ | ------------
696 | 520001005003036 | xxx | xxx
696 | 520001005003036 | xxx | xxx
696 | 520001005003036 | xxx | xxx
697 | 520001005001234 | xxx | xxx
697 | 520001005001234 | xxx | xxx

特点是
- 针对一个用户ID有一到N条记录，分别记录了用户所有社区编号和其他业务数据  
- 这个任务只需要关心用户ID，所有社区编号，创建时间三个字段  
- 数据保存在 mongdb 数据库中  

需要使用阿里云数+平台来对数据进行统计分析，来达到以下目的：
- 统计每个社区包括多少用户，把统计结果数据保存到一个 mongdb 表
- 后续还有很多统计工作都要在数+平台进行，需要借助这个任务制定一个开发规范指导后续开发
- 原始数据会定期增量增加，所以需要统计支持增量统计

#### 1.1、选型/环境

- 阿里云数+平台

#### 1.2、文档

- 通过沟通确认需求，提交需求理解文档
- 确定需求理解后，完成设计，提交数据库设计文档

#### 1.3、开发

- 完成阿里云数+开发和对应说明文档
- 提交阿里云数+开发规范

#### 2.1、阶段和验收

周期：7 天（明确需求后，以开发者承诺为准）

#### 2.2、调整和处罚（码市）

- 可以进行一次时间调整申请，最长不超过 2 天。
- 未申请或已经有过调整的，每延期一天按项目金额的 10% 进行罚款。
- 超过 5 天，需求方有权取消项目。
- 需求方原因造成的延误不包含在内。

#### 3.1、人员要求

- 证明自己有能力胜任此项工作
- 通过沟通与思考明确需求
- 明确需求后，在承诺的时间完成提交
- 熟悉 github, github 账号时间大于半年（在报名中给出 github 账号）
- 熟悉 阿里云

报名人员可到：
[github.com/social-innovation/tasks/issues/25](https://github.com/social-innovation/tasks/issues/25)
直接进行需求讨论

### 4、费用

2000 元（理解需求后按实际承诺工作量计算）

### 5、协作工具

- zoom: https://zoom.us/
- 石墨文档: https://shimo.im/
- github: https://github.com/
- 微信

**Comment by fushang318** [comment]
@ben7th 你看看

**Comment by ben7th** [comment]
是数+ 平台，而不是树+ 平台。。

**Comment by fushang318** [comment]
对任务进行了优化 https://github.com/social-innovation/tasks/issues/26
此ISSUE 关闭
