### ISSUE TITLE
对文章进行断句以及逐句情感分析

### ISSUE THREAD

**Issue by ben7th** [social-innovation/tasks#3]
### 背景

有一些各种来源的文章，想从某方面了解文章内包含的叙述的情感倾向

### 目的

对文章进行断句，逐句进行情感分析，达到以下目的：
- 输出断句后的每个句子
- 输出每个句子的情感倾向（正面概率/负面概率）
- 计算整个文章的情感倾向

### 实现

- 使用腾讯文智的服务 http://nlp.qq.com/help.cgi?topic=api#sentiment
- 使用 python3 实现
- 通过命令行指定参数，以对任何传入的 txt 文件进行分析
- 自行设计符合逻辑的断句方法
- 将分析结果输出成 json

### 要求

- 证明自己有能力进行此项工作
- 通过思考与沟通明确需求
- 明确需求后，在承诺的时间完成开发

**Comment by Zhouyl94** [comment]
宋哥，我们找到一个合适的算法，代码是python2，正在调试，具体的已经上传到文本分析情感算法模块。刚才又搞错了......@ben7th

**Comment by Zhouyl94** [comment]
@ben7th 宋哥，我们找到一个合适的算法，代码是python2，正在调试，具体的已经上传到文本分析情感算法模块。刚才又搞错了.....

**Comment by ben7th** [comment]
@Zhouyl94 

若是任务响应，请说明：

- 思考，理解，或问题
- **什么时间提交什么内容**

若是提交，需要是合理的提交，见：
https://github.com/social-innovation/cooperation-buaa/issues/7#issuecomment-351633816
这里的回复

**Comment by ben7th** [comment]
已在这里回复
https://github.com/social-innovation/cooperation-buaa/issues/7#issuecomment-351633816
