### ISSUE TITLE
用程序生成符合一定特征的传播网络/圈子数据

### ISSUE THREAD

**Issue by ben7th** [social-innovation/tasks#9]
### 背景

目前正针对传播网络/圈子进行可视化视图的开发，需要为视图准备一些符合特征的实验用展示数据

### 目的

用程序生成一些数据，达到以下目的：
- 数据结构符合 https://github.com/social-innovation/public/wiki/communication-network-visual-modeling 中的模型结构
- 生成 200 个左右节点
- 在节点间生成关联关系和圈子
- 圈子中包含的节点需要是连通的
- 生成 4-5 种关系类型

### 实现

- 编写代码生成需要的数据
- 输出 JSON 格式文件
- 提交代码和生成的数据
- 数据以及数据生成方法要有合理性

### 要求

- 说明如何进行这项工作，描述生成方法
- 在承诺的时间完成开发
- 配合与可视化视图的对接

**Comment by doomooo** [comment]
@ben7th 
好的

**Comment by doomooo** [comment]
@ben7th 
Link:
  from: 关系起点的节点 id，对应 Point.id
  to: 关系终点的节点 id，对应 Point.id
  type: 关系类型，对应 LinkType.name

这个是有向图还是无向图啊？

**Comment by doomooo** [comment]
@ben7th  已经弄好了
[代码地址](https://github.com/social-innovation/d-net-group/tree/network-visual-data/%E5%8F%AF%E8%A7%86%E5%8C%96%E6%95%B0%E6%8D%AE)

**目的**

为可视化做准备一些符合特征的实验用展示数据

> 其中需要满足

- 数据结构符合 https://github.com/social-innovation/public/wiki/communication-network-visual-modeling 中的模型结构
- 生成 200 个左右节点
- 在节点间生成关联关系和圈子
- 圈子中包含的节点需要是连通的
- 生成 4-5 种关系类型


---

**基本假设**

- 圈子中的人存在交叉
- 一个圈子对应一个关系类型
- 圈子中的人在地理位置上，也大体在一个圆圈范围以内，各成员距离圆中心的距离满足高斯分布（若一个节点在多个圈子里，则圆中心由各圈子加权而来）



**具体操作**

> 生成节点类型数组、关系类型数组

- 节点中节点类型 选择方法：节点编号整除节点类型长度的余数
- 圈子对应关系类型方法：圈子编号整除关系类型长度的余数


> 生成圈子

- 随机生成圈子里的成员
- 圈子的额外属性包括：关系类型、圆圈中心、平均半径、权重

> 生成关系

- 根据假设，圈内成员之间的关系都具有统一的关系类型

- 设置了一个连通率，当连通率为1 时，圈内成员两两相连，当连通率为0时，则圈内成员串联在一个连通路径上

> 生成节点

- 根据假设，利用圈子的圆中心位置随机生成节点位置

**Comment by ben7th** [comment]
@doomooo 已经看到提交了。

有起点和终点，所以是有向图。

**Comment by ben7th** [comment]
@doomooo 已经合并
https://github.com/social-innovation/d-net-group/pull/11/

在这里回复一下你的工作量（8 小时算一天）

**Comment by doomooo** [comment]
@ben7th 

1天

**Comment by ben7th** [comment]
此工作已完成，此 issue 关闭
